language: java
jdk:
- oraclejdk8
- openjdk8
- oraclejdk9
cache:
  apt: true
  directories:
  - "$HOME/.m2"
sudo: required
addons:
  apt:
    packages:
    - jq
    - libxml2-utils
matrix:
  allow_failures:
  - jdk: oraclejdk9
before_install:
- ./ecr_credentials.sh
script:
- build_head=$(git rev-parse HEAD)
- git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch origin dev
- git checkout -f dev
- git checkout $build_head
- git merge dev
- mvn integration-test -Dlogging-level=INFO
- VERSION=`echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:version/text()'
  | xmllint --shell pom.xml | grep -v / | tr -d -`
- echo $VERSION
- git clone https://github.com/iotaledger/iri-regression-tests.git
- cd iri-regression-tests
- git checkout -f master
- mkdir iri
- cp -rf ../target iri/target
- bash run_all_stable_tests.sh $VERSION
- cd ..
after_success:
- test $TRAVIS_PULL_REQUEST = "false" && test $TRAVIS_JDK_VERSION = "oraclejdk8" &&
  wget -O codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
  | jq -r .assets[0].browser_download_url)
- test $TRAVIS_PULL_REQUEST = "false" && test $TRAVIS_JDK_VERSION = "oraclejdk8" &&
  java -jar codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml
deploy:
- provider: releases
  api_key:
    secure: j+KolvRrsinh6OTqjli1y5I4gdPdD5MT6RFahVRrznxtcb2t7y6x41PknkI/8BksxLJKKQ1f40L307Aquzih9FmLesWcrYrCOS/B40dlCc3uV8DEZKhZF+QWqvsDpZ0EfiluGFljqGpxwngb/miNObqQzQvzpdUXBpZcuzxgqziynJD6jt3TYbNn544m/i4cWbb++b1h2Bm+jwELzJcf6/CZ1TxUh49vdM4S6yTpvnKwg4NLeH6g8s9oYEN1iwYtQokGKlH/emBZDsqDtF4KH7kXPpEKTcho4nH504XWJpanVAQ02Pha4SAnyVu4rKiLH4e6v99xZOBLVTH/qkvlwzvkNYr2xS5q9T9G7DZBRE+oc2MIbcnuSkhHwrUcmf2Hc0zCIP4RLCXAUuVlNEmIQUKgTezVzaqaEQLsa+EFIoosS+8pT/kVnaLbwxrITUmgM246+gvzMcVg8SmyPvVj6iRxfR6spTd7V2M0ePdqWlCL8P9RY4YrtxR2yJ6/3C0XNf29t+s/r1jat8fwWp8Gf7GiCaJEYG9VO24Chhi+MZCKBJnmx5G/98zvLw3f6a1FsEGZrw9RhF2vJKK6sD3rIvNkUsYmf0OhM7bf0NceFMGTJ/mFzM/JX0OHMtIyAvUfyyPVbQkIHNcGBgQMZasx07K3fjcn2lqv4FbHVi3HbdM=
  file_glob: true
  file: target/*.jar*
  skip_cleanup: true
  before_deploy: openssl aes-256-cbc -K $encrypted_5a15fa813cca_key -iv $encrypted_5a15fa813cca_iv
    -in codesigning.asc.enc -out codesigning.asc -d && gpg --fast-import codesigning.asc
  deploy: mvn package -P build-extras -Dlogging-level=INFO
  on:
    tags: true
    repo: iotaledger/iri
    branch:
    - master
env:
  global:
  - secure: oJutGSe5KK3ymwSvohFZ89UL7XaNlXH6fdO2nBEYbk5KyYuQ1Wm+h6+N/05EbwxwDK9dEiF73ZJh76sZ3IWKjRC8VWjUAz+8p38hGvQwByrVsJkrbs5SA4wA4XnyvEqyMV3yqbcgRNbMlIvj7ubUbxMizz7MA7plnumrnx9ejPG1WP4rNgzUA3XcBWHdITyOSg9rSMBJzMZ9CN1Dv+1SxZV+GlkyWN8n1Cshkq2TnNl1oRZqGKs7O0ma1dN0hUKtBa80AsCTjH8ojZFJU92gmkvAWDw5BTSZ8mhX9sZcbBYT8SnQxNDrf51HJ+K7hvdpFbsy5Z0g24cNJkA8lfUnzXFznZ/PH4hm8MeVWjRiWdE4VZr47iYzJcs0brOHSeab6fBoeTPS5899Q3V+yAw6CahfvOBthuF3Ymy+fZXoDO5242PSWXXsGwFqK7r/gT0iwJZxMBI/UUWsP/s7J/CWux8ftwbOdSbs4XdQZsuqxzKEKDDwU0FTytantsMS/vcgI41K5azyY4tbkixzydaBPvhimkflaWcuZb//mXcntitgyenaSwfkLX5pD5l1srVzSliyabnH7AprLOm1B9DBfk2leI2XgGJg/Q/GrVtcjcl1FU0aXBFhLrp3BkK7chlG2v/Eacr8Pb6NOQHORyq64n2prF6zvExX0aadOddefoA=
  - secure: HfmR15dSUnVLXtYzqE8Rq6STPunSNWpKTipNim79SZ+KE/pJpRQCpcRpePCzjdGAOfEOo6JyCoT0AeYkES+QU59hoKZPa8TLv+X+8YRW4CSn3mCxibdwfWERwzBeZ9zE//glVu3iIiEyzMo75NZcgL/dTR4oJ9jynl99g6atuWCWzIqDgh7/HbdnTP8vEjsHrQ+mCrPxg3LBGUH89EQdRriLEkNPmNpZG/VKktE/voPSK5JQF0EGAuidXbDHkjA4k6JY9xBgXj/RojYC6w/OrS2V+u4apwGrhyOFH5tKxgImg2UxxNtgOMJPm7nLk5ofahFLnsULptjNnqRqASVviOD7Ho11BYKF/O0lMOx5XmB0NeKfI9zymbXbpqf5TPi7HOudy7LFEz7fL6jmseme81OXL3VC+1vcPqMh534FGqrRMmf9nTIo75pi4bwPUj2HcCMAsQV9QEdkcovydPc8qYqERXNAMCP7Pl44z9kEf6EsJ6RgBfb+wBTf1lLTy5ZUG8r894m+5lQC95FdQOKTsOVUqR/W8DVIrYXcYHLIBxfnG0NR2yqjh9aiTCyvN/QQmJUYAWiyJ0yeZf6ez1rS6Qiyik9Uc/8dn0jVqL5pL3lj+MuUPQL4ES/wJeHgioLxB5oQX2fgIL+2XQ/EWaMKGPe2IuEdmS+wXsTRr1FCouE=
  - secure: GZTo/3OIdK8gy/ESDsf1bgBtfi8QdKUkq38ZNv8RCMGxeswPLXAP2FcSwi2hdlTrXC93pCUQAEcy9L5/5Xd1zPUKUgmk7sTuxMDaEEfVyiP1PMee4kqtJAvpro83o2B6o0vryUkf65wDZXBBTfu8C9whQjsTxanpkJ99faKSF5BUans0VtardUZOML72eDE5MVBclMYznguiTb0zz1FRkSdMOPcXheRGSQjxD57QYiqI33BRRv7ysHl3lTr1vfbDxsTAN3miW+cukiZOZLnWw6fUoP4AeetoHQSmuEjE3L13Szv+zvV639SdeJ4qp81yJVMDL3B1qC7r3dIATQ3Rz26MMp+3FXHxau87EiC5lMhk9z9PV5SxFXZ3ZrPQLCBf5a7wjte7ouYDhvJVmNdfqA1szppwvWHeRRgCsYmgy3tKOubCf51SKTfFvCRunxlj/2e8PDs5T+XVl+9b4jbKg0u3fhhhFLeko+puGFEX3XobmH+8uqqR+3lAAgQ2y7oj+ZNih+ElS7cHJxaAbomhTZbk6pu4C8R54zeBnLlPKFLHdrjQd1+O2ylU2Tgewnz98n73THwKT+MOtwnmPRpnZ3yVhBCeqqT6LodwDcI4R6nL8XZew5A49XdMEwHOJnLXt7jABGspBgMqUhwIc7PMuN0MOBq2D8uQIIPzP/YAFQ0=
  - secure: GT+ASeXWWBsqnv1VIiKOkHZexvopgQCTcmxL8kjjWYd4yoZYihMNN6n35u6E8T0Q02l7LrbRgtT7EvpMJYqdrQEBmqRwipVNKCLsffuLSRgpRWAwlz1CIX9qex3IyxyxpyYoZr4UOIc4ERvEOPAjKnoCYoRRqaanZ6I1fuI1Hgn3tYHgcnBfBUS2qeycxn4pXIVTBmjvwulss2FRS4K0hbxo3cfPjXdnmjiBaUOMD7qGyMPS++3vQuIReygsIHB0rkb8F00te+x9uZXuzoABT0q0xPTedqC4Io0DLDSyRILxIeQg6mQUCHLHQ9rTAEaSo26huKUf9PSjeSn5Q99JDupTPmcM9HwtBGP5RxqW9geB74mbwvXQbg9R9Ut0MWOMfl5q/gyjL3Ddv6g4qN+ebt9D40KRoCpPd5wDDaBcB3XzGePFbqndQtX12La2tELBO8MzvZZEGvgNIv1kX1ASu2MliUsqABES04VMM9qQTCyQcO0gd96JWeexqdGHabirbkRizQkZ36O/Du5BI4xxdlBK/rNU0P5fvqSdmqV+gBy434/D6l/qeoABa3eooceR63DoeHidAB+4KvhMVizkiUpOF5lJ1COWzPOjmiH6dBgq1+47IOw1xQ73fnxIWcCQjg/YSL6N/qD1LuKAjipGDz2GGYUhnHqOPp/Gn5cl2DA=
